### ISSUE TITLE
Discard low relevance questions

### ISSUE THREAD

**Issue by swetul** [pratikpatelx/AnswerBot#9]
Need to decide on a relevance metric figure to be able to discard low relevance questions.
some thoughts:
- less than 50% relevance -> discard question
- between 50-75% relevance -> debate-able
- more than 75% relevance -> must pass on to next question

please comment on thoughts and solutions @pratikpatelx

**Comment by pratikpatelx** [comment]
We can go with the less than 50% relevance. If we get a relevance between user query q and Question Q less than 50% we can  discard that Question. What do you think?

because based on the symmetric relevance between the query and each question in the database, we need to rank the top N questions as the relevant questions for the query

@swetul

**Comment by swetul** [comment]
As discussed, we will use top 10 relevant questions. 
Closing issue
